(require 'diminish)

(eval-after-load "beacon"              '(diminish 'beacon-mode))
(eval-after-load "git-gutter"          '(diminish 'git-gutter-mode))
(eval-after-load "helm"                '(diminish 'helm-mode))
(eval-after-load "paredit"             '(diminish 'paredit-mode))
(eval-after-load "rainbow-mode"        '(diminish 'rainbow-mode))
(eval-after-load "undo-tree"           '(diminish 'undo-tree-mode))
(eval-after-load "volatile-highlights" '(diminish 'volatile-highlights-mode))
(eval-after-load "which-key"           '(diminish 'which-key-mode))
(eval-after-load "ws-butler"           '(diminish 'ws-butler-mode))
